### ISSUE TITLE
Needs FreeRADIUS 3 when it has FreeRADIUS 3.0.11

### ISSUE THREAD

**Issue by mjh75** [djjudas21/puppet-freeradius#35]
I have been using puppet for about 6 months and figured radius is a good candidate to "puppetize". I am running Ubuntu 15.10 which I know is not officially supported but it should be possible to fix things so that it will work. I have not written any modules so am limited in my knowledge in that area.

I have FreeRADIUS 3.0.11 installed on a client but when running the agent I get a message saying that it is only compatible with FreeRADIUS 3. I have changed that error to a warning, but then get into all kinds of missing things for logrotate. Any suggestions where to start?

$ freeradius -v
radiusd: FreeRADIUS Version 3.0.11, for host x86_64-pc-linux-gnu, built on Mar 25 2016 at 19:13:16
Copyright (C) 1999-2016 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
$ sudo /opt/puppetlabs/bin/puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, This module is only compatible with FreeRADIUS 3 at /etc/puppetlabs/code/environments/production/modules/freeradius/manifests/init.pp:17:5 on node sdga.vsdb.ca
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
$

**Comment by djjudas21** [comment]
Sorry to hear this! Please can you confirm which version of the `freeradius` module you are using? There was a bug with interpreting version numbers and it was fixed a little while ago.

**Comment by djjudas21** [comment]
Please can you also give the output of:

```
facter freeradius_version
facter freeradius_maj_version
```

**Comment by mjh75** [comment]
Looks like 2.1.2, I did just upgrade it yesterday from 2.1.1.

jgazeley-freeradius (v2.1.2)

Nothing is coming back from the requested facter.
# /opt/puppetlabs/bin/facter freeradius_version

# /opt/puppetlabs/bin/facter freeradius_maj_version

#

**Comment by djjudas21** [comment]
Hmm OK. 2.1.2 has the fix for version numbers in.

1. Can you confirm the full path to your `freeradius` binary?
2. Does the command `radiusd -v` do anything on your system?
3. Did you build your own FreeRADIUS on the server with `make`/`make install` or did you build a .deb?

**Comment by mjh75** [comment]
1) /usr/sbin/freeradius

2) $ radiusd -v
The program 'radiusd' is currently not installed. You can install it by typing:
sudo apt-get install radiusd-livingston

3) I built my own .deb and am using it on a number of servers. I have my own internal repository.

**Comment by djjudas21** [comment]
It seems to me that the problem is with the custom facts that report the version number (https://github.com/djjudas21/puppet-freeradius/blob/master/lib/facter/freeradius_version.rb)

On RedHat/CentOS the binary is installed as `radiusd` so the custom fact checks `radiusd -v` and then `freeradius -v` to find the version number. On RedHat, if you guess the wrong path to the binary it doesn't do anything and the custom fact will try the next value. On Ubuntu, it looks like it's printing a clever message to suggest where you can find `radiusd` so the fact is trying to parse that, rather than recognising that as a failure. I think I can fix this with a `:confine` statement.

**Comment by mjh75** [comment]
I am more than happy to test it for you. My knowledge of ruby is rather limited so not sure where to start to be honest.

**Comment by djjudas21** [comment]
OK I've just pushed ba3ccd0 which seems to work on my dev Ubuntu VM. It should make the facts render properly, which will then allow the Puppet module to make decisions based on the version number of FreeRADIUS. Please can you test this version and let me know if works. If so, I'll tag a new release.

**Comment by mjh75** [comment]
I downloaded the replacement freeradius_version.rb and stuck it in on the server. Ran puppet agent -t and watched the file get changed. Ran puppet agent -t again to update anything else. I still get blank output from facter freeradius_version and facter freeradius_maj_version.

**Comment by djjudas21** [comment]
And `facter osfamily` definitely returns `Debian` for you?

**Comment by djjudas21** [comment]
Also is `freeradius` in your path, and picked up correctly by doing `which freeradius`?

**Comment by mjh75** [comment]
Yes 
$ sudo /opt/puppetlabs/puppet/bin/facter osfamily
Debian

$ which freeradius
/usr/sbin/freeradius

Also in the path as root.

**Comment by djjudas21** [comment]
I can't see any reason why the fact is not evaluating properly, all the paths are correct. I'm not at all familiar with Debian/Ubuntu but could it be something to do with AppArmor etc? SELinux on RedHat has been known to block Puppet/Facter from doing execs on random binaries.

It's Friday evening here and I'm off for the weekend - let's pick this up on Monday.

Cheers,
Jonathan

**Comment by mjh75** [comment]
I have found a work around for my situation so am happy for now. Enjoy your weekend. If I discover anything this afternoon I will post it here but certainly don't expect an answer over the weekend. :)

**Comment by mjh75** [comment]
Running puppet facts --debug yields:

Info: Facter: loading custom facts from /opt/puppetlabs/puppet/cache/lib/facter/freeradius_version.rb.
Debug: Facter: executing command: /bin/sh -c /usr/sbin/freeradius -v
Debug: Facter: radiusd: FreeRADIUS Version 3.0.11, for host x86_64-pc-linux-gnu, built on Mar 25 2016 at 19:13:16
Copyright (C) 1999-2016 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Debug: Facter: process exited with status code 0.

So that looks like it is running just for some reason the version number cannot be parsed.

**Comment by djjudas21** [comment]
Thanks for the extra info. I've had a look at it and I can't see where the problem might be coming from. Please can you confirm your version of Ruby? Is it the Ruby that came installed on Ubuntu 15.10? And I probably should have asked earlier, but what version of Facter?

**Comment by mjh75** [comment]
$ ./ruby --version
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]


$ /opt/puppetlabs/bin/facter --version
3.2.0 (commit 5e45299d765993d17f1f1337eaee6a64363904a2)

Both are the versions included in the package from the apt repository that I installed from apt.puppetlabs.com.

**Comment by djjudas21** [comment]
Hmm OK. I'm on 2.0.0 and Facter 2.4.6 so it's possible there's a change in behaviour. To be honest I'm a bit stuck and I don't have any Debian/Ubuntu machines to play with for debugging. I'll probably punt this towards the `puppet-users` mailing list. Are you a subscriber there?

**Comment by mjh75** [comment]
Not yet. I will get myself on it soon.

**Comment by djjudas21** [comment]
I've done some more testing and found that the fact does work on Debian 9 (unstable) with Facter 3.1.5 and Ruby 2.3.0 and on CentOS 7 with Facter 3.2.0 and Ruby 2.0.0. So this rules out a general incompatibility with Facter 3.x.

**Comment by legooolas** [comment]
For info, this fact works OK for me when added as a custom fact on a Debian unstable box:

# facter --custom-dir=. freeradius_version
2.2.8
# facter --custom-dir=. freeradius_maj_version
2
# ruby --version
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]
# facter --version
3.1.5 (commit b5c2cf9b2ac290cb17fcadea19b467a39e17c1fd)

**Comment by djjudas21** [comment]
I also managed to get access to an Ubuntu 16.04 VM with Facter 3.2.0 and Ruby 2.3.0. The fact resolves properly on this platform, too.

**Comment by djjudas21** [comment]
@ross-w sent PR #36 which fixes compatibility with checking version numbers. Sounds like it might be related the problem you're having? I've just released 2.1.3 as a tag here on Github and on Puppet Forge, so can you give this a try and let me know how you get on? Thanks

**Comment by mjh75** [comment]
I have upgraded the module to 2.1.3 and am still getting the same results. I will see what I can do about upgrading to 16.04 and see if that helps. Since I found a workaround I am not in as big of a rush to make this work.

Thanks

**Comment by djjudas21** [comment]
Closing this issue as the codebase has moved on and we are now on 3.x
